esphome:
  name: esp32-gzm

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "tijolo22"

ota:
  - platform: esphome
    password: "tijolo22"

wifi:
  ssid: "nome_rede"
  password: "senha_123"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Devkitc-V4"
    password: "2yBYiZIDp2nE"

captive_portal:

web_server:
  port: 80
  version: 3

# one_wire:
#   - platform: gpio
#     pin: GPIO17

i2c:
  - id: bus_a
    sda: GPIO14
    scl: GPIO13
    scan : true

  - id: bus_b
    sda: GPIO32 
    scl: GPIO33   
    scan: true

sensor:

  - platform: wifi_signal
    name: "Wifi Signal"
    update_interval: 60s

  - platform: internal_temperature
    name: "Internal Temperature"
  
  - platform: vl53l0x
    i2c_id: bus_b
    name: "VL53L0x Distance"
    address: 0x29
    update_interval: 5s
    long_range: true

  - platform: bmp280_i2c
    i2c_id: bus_a
    temperature:
      name: "Temperatura"
      oversampling: 16x
    pressure:
      name: "Pressão"
    address: 0x76
    update_interval: 5s

  # - platform: dallas_temp
  #   address: 0x1234567812345628
  #   name: "Termometro"
  #   update_interval: 5s

