esphome:
  name: lhc3

esp32:
  board: esp32-c3-devkitc-02
  framework:
    type: esp-idf

# Enable logging
logger:
  level: VERBOSE
  logs:
     component: ERROR

# Enable Home Assistant API
api:
  password: "tijolo23"

ota:
  - platform: esphome
    password: "tijolo23"

wifi:
  ssid: "IoT"
  password: "tijolo22"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lhc C3 Home Fallback Hotspot"
    password: "IuMdjTzqwGf9"

captive_portal:

web_server:
  port: 80
  version: 3


i2c:
  sda: GPIO0
  scl: GPIO1
  scan: true
  
sensor:
  - platform: wifi_signal
    name: "Wifi Signal"
    update_interval: 10s

  - platform: internal_temperature
    name: "Internal Temperature"
    
  - platform: adc
    pin: GPIO4
    name: "Battery Voltage"
    update_interval: 5s
    
  - platform: bmp280_i2c
    temperature:
      name: "Temperatura"
      oversampling: 16x
    pressure:
      name: "Pressão"
    address: 0x76
    update_interval: 5s

